# Generated by Django 3.2.6 on 2021-08-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_clr', models.CharField(max_length=2)),
                ('nom', models.CharField(max_length=10)),
            ],
        ),
    ]
