# Generated by Django 3.2.6 on 2021-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_categorie_fr_client_collection_depot_famille_magasin_societe_taille_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='Raison_sociale',
            field=models.CharField(max_length=100),
        ),
    ]
