# Generated by Django 3.2.6 on 2021-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_societe_raison_sociale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='depot',
            name='qte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magasin',
            name='qte',
            field=models.IntegerField(default=0),
        ),
    ]
