# Generated by Django 3.2.6 on 2021-08-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210818_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Magasin',
        ),
    ]
