# Generated by Django 3.2.6 on 2021-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_magasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=20)),
                ('qte', models.IntegerField(default=0)),
                ('Adresse', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=20)),
                ('Pays', models.CharField(max_length=20)),
                ('Tel', models.CharField(max_length=20)),
                ('Fax', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
