# Generated by Django 3.2.6 on 2021-08-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_magasin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magasin',
            name='Pays',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='Ville',
        ),
    ]
