# Generated by Django 3.2.6 on 2021-08-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210818_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raison_sociale', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=20)),
                ('Pays', models.CharField(max_length=20)),
                ('Tel', models.CharField(max_length=20)),
                ('Fax', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('page_accueil', models.CharField(blank=True, max_length=50, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.categorie_fr')),
            ],
        ),
    ]
