# Generated by Django 3.2.6 on 2021-08-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_fournisseur_page_accueil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=10)),
                ('Code_Produit', models.CharField(max_length=20)),
                ('Code_Barre', models.CharField(max_length=13)),
                ('Designation', models.CharField(max_length=20)),
                ('Libelle_Ticket', models.CharField(max_length=20)),
                ('Prix_Untaire', models.FloatField()),
                ('Prix_HT', models.FloatField()),
                ('Prix_TTC', models.FloatField()),
                ('Collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.collection')),
                ('Famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.famille')),
                ('Style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.style')),
                ('Tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tva')),
            ],
        ),
    ]
