# Generated by Django 3.2.5 on 2021-08-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='contenir_clr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.couleur')),
                ('prdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produit')),
            ],
        ),
    ]
