# Generated by Django 3.2.5 on 2021-08-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_association_mag_depot'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockagePrdtDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.depot')),
                ('prdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_recep', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ligne_recep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qte', models.IntegerField()),
                ('prdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produit')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reception')),
            ],
        ),
    ]
