# Generated by Django 3.2.5 on 2021-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_ligne_recep_reception_stockageprdtdepot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='page_accueil',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
