# Generated by Django 3.2.5 on 2021-08-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_fournisseur_page_accueil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='page_accueil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
