# Generated by Django 3.2.5 on 2021-08-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_fournisseur_page_accueil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_Livr', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='reception_magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.livraison')),
                ('mag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='reception_clt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('livr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.livraison')),
            ],
        ),
        migrations.CreateModel(
            name='ligne_livr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qte', models.IntegerField()),
                ('livr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.livraison')),
                ('prdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produit')),
            ],
        ),
    ]
