# Generated by Django 3.2.5 on 2021-08-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_ligne_livr_livraison_reception_clt_reception_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='depot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.depot'),
            preserve_default=False,
        ),
    ]
