# Generated by Django 3.2.5 on 2021-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_produit_code_barre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Code_Barre',
            field=models.BigIntegerField(default=3250000000000, max_length=13),
        ),
    ]
