# Generated by Django 3.2.5 on 2021-08-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_produit_code_barre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Code_Barre',
            field=models.BigIntegerField(default=3250000000000),
        ),
    ]
